# Site settings
baseurl = "https://blog.stanzheng.com/"
languageCode = "en-us"
title = "Stanley Zheng"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-73744856-3"
# Disable comments by leaving disqusShortname empty
disqusShortname = "stanzheng-com"
paginate = 8

[params]
	name = "Stanley Zheng"
	description = "Programmer Blog, trying to share insights and knowledge picked up along the way."
	bio = "Developer - Foodie - Friendly Human"
	# Enter optionally your twitter account
	twitter = "stanzheng"
	enableRSS = true
	aboutURL = "https://stanzheng.com"
	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Polyglot who loves to experiment and explore."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/stanzheng"
    facebook = "https://www.facebook.com/stanley.zheng.usa"
    github   = "https://www.github.com/stanzheng"