---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: blog/content/2020
  label: '2020'
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/recurse
  label: Recurse
  create: all
  match: "**/*"
- type: directory
  path: content/2018
  label: '2018'
  create: all
  match: "**/*"
- type: directory
  path: content/2017
  label: '2017'
  create: all
  match: "**/*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: content/2019
  label: '2019'
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
