---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: datetime
  name: date
  label: date
- name: tags
  type: text
  config:
    required: false
  label: tags
- name: draft
  type: text
  config:
    required: false
  label: draft
  default: 'true'
pages:
- content/2019/interactive-fun-ways-to-learn-sql.md
- content/2019/standardizing-your-units.md
