---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: datetime
  name: date
  label: date
- name: tags
  type: text
  config:
    required: false
  label: tags
- name: draft
  type: text
  config:
    required: false
  label: draft
  default: 'true'
